version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "avzeus2-ai"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ske8734iegyh"
s3_prefix = "avzeus2-ai"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
