AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  avzeus2-ai

  Sample SAM Template for avzeus2-ai

# ローカルテスト時、Building image... のとこで処理時間が間に合わずエラーが起きるのを回避できるように長めに設定
Globals:
  Function:
    Timeout: 30

Resources:
  # HelloWorldFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     CodeUri: hello_world/
  #     Handler: app.lambda_handler
  #     Runtime: python3.9
  #     Events:
  #       HelloWorld:
  #         Type: Api
  #         Properties:
  #           Path: /hello
  #           Method: get
  #     Layers:
  #       - !Ref MyLayer

  # MyLayer:
  #   Type: AWS::Serverless::LayerVersion
  #   Properties:
  #     Description: Layer description
  #     ContentUri: "my_layer/"
  #     CompatibleRuntimes:
  #       - python3.9
  #   Metadata:
  #     BuildMethod: python3.9

  InitActressRecommendFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: "zeus/init_actress_recommend/"
      Handler: algorithms.lambda_handler
      Runtime: python3.7
      Events:
        InitActressRecommend:
          Type: Api
          Properties:
            Path: /init-actress-recommend
            Method: get
      # Layers:
      #   - !Ref InitActressRecommendDep

  ImgRecommendFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: "zeus/img_recommend/"
      Handler: algorithms.lambda_handler
      Runtime: python3.7
      Events:
        InitActressRecommend:
          Type: Api
          Properties:
            Path: /img-recommend
            Method: get

  # InitActressRecommendDep:
  #   Type: AWS::Serverless::LayerVersion
  #   Properties:
  #     Description: A dependenceis layer for InitActressRecommend
  #     ContentUri: "dep/zeus/init_actress_recommend/"
  #     CompatibleRuntimes:
  #       - python3.9
  #   Metadata:
  #     BuildMethod: python3.9

  # ImgRecommendDep:
  #   Type: AWS::Serverless::LayerVersion
  #   Properties:
  #     Description: A dependenceis layer for ImgRecommend
  #     ContentUri: "dep/zeus/img_recommend"
  #     CompatibleRuntimes:
  #       - python3.9
  #   Metadata:
  #     BuildMethod: python3.9
